---
server:
  port: ${PORT:8080}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mklisura1/java-microservices-config-server
          search-paths:
          - 'station*'
          